<div class="allFestivalIndex">
    <div class="width">
        <div class="title">{{$data['title']}}</div>
        <div class="festivalContainer">
            <div class="firecracker">
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
            </div>
            <div class="countdown2" data-time="{{$data['height']}}"></div>
            <div class="firecracker">
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
                <span><i></i></span>
            </div>
        </div>
    </div>
</div>
